name: Prod Pipeline Deploy

on:
  push:
    branches: [prod]

jobs:
  Deploy:
    name: Prod Deploy
    environment: Prod
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Lint
        run: |
          pylint ./src --fail-under 8

      - name: Initialize Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest

      - name: Deploy Terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
        run: |
          cd terraform/
          terraform init -backend-config="access_key=${AWS_ACCESS_KEY_ID}" -backend-config="secret_key=${AWS_SECRET_ACCESS_KEY}"
          terraform fmt -diff ./
          terraform plan --out=tfplan -var-file="prod.tfvars"
          terraform apply tfplan
