name: Sandbox Pipeline

on:
  pull_request:
    branches: [sandbox]

jobs:
  Lint:
    name: Lint
    environment: Sandbox
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Lint
        run: |
          pylint ./src --exit-zero

  Terraform:
    name: Terraform
    environment: Sandbox
    runs-on: ubuntu-latest
    needs: Lint
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Initialize Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest

      - name: Plan Terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd terraform/
          terraform init -backend-config="bucket=terraform-state-bucket-aws-cloud-sandbox" -backend-config="access_key=${AWS_ACCESS_KEY_ID}" -backend-config="secret_key=${AWS_SECRET_ACCESS_KEY}" -backend-config="region=us-east-2"
          terraform fmt -diff ./
          terraform plan --out=tfplan -var-file="sandbox.tfvars"
