name: Sandbox Pipeline Plan

on:
  pull_request:
    branches: [sandbox]

jobs:
  Lint:
    name: Lint
    environment: Sandbox
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Lint
        run: |
          pylint ./src --fail-under 8

  Zip:
    name: Zip
    runs-on: ubuntu-latest
    needs: Lint
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Zip File
        run: |
          mkdir build
          cp -rf src build
          zip ../src.zip -r .
          cd ..
          mkdir -p layers/python
          cd layers
          pip install -r ../src/requirements.txt -t python
          zip ../lambda_layers.zip -r

  Terraform:
    name: Terraform Plan
    environment: Sandbox
    runs-on: ubuntu-latest
    needs: Zip
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Initialize Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest

      - name: Plan Terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd terraform/
          terraform init -backend-config="access_key=${AWS_ACCESS_KEY_ID}" -backend-config="secret_key=${AWS_SECRET_ACCESS_KEY}"
          terraform fmt -diff ./
          terraform plan --out=tfplan -var-file="sandbox.tfvars"
