name: Sandbox Pipeline

on:
  pull_request:
    branches: [sandbox]

jobs:
  Lint:
    name: Lint
    environment: Sandbox
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Lint
        run: |
          python lint.py --path ./src --threshold 2

  Terraform:
    name: Terraform
    environment: Sandbox
    runs-on: ubuntu-latest
    needs: Lint
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Initialize Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest

      - name: Plan Terraform
        run: |
          cd terraform/
          terraform init -backend-config='bucket=terraform-state-bucket-aws-cloud-sandbox'
          terraform fmt -diff ./
          terraform plan --out=tfplan -var-file="sandbox.tfvars"
